version: '3'
services:
  rest:
    build: .
    ports:
      - "5003:5003"
#  db:
#    image: mysql
#    restart: always
#    environment:
#      MYSQL_DATABASE: ${MYSQL_DATABASE}
#      MYSQL_USER: ${MYSQL_USER}
#      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
#    ports:
#      # <Port exposed> : <MySQL Port running inside container>
#      - '3306:3306'
#    expose:
#      # Opens port 3306 on the container
#      - '3306'
#      # Where our data will be persisted
#    volumes:
#      - my-db:/var/lib/mysql
## Names our volume
#volumes:
#  my-db:


